JavaEngine: fix critical buffering bug
This fixes Fiji bug #1029:
http://fiji.sc/bugzilla/show_bug.cgi?id=1029

The CharBuffer has a position which does not get reset, and so length()
returns 0 even when there is data in subsequent read passes. We avoid
the issue by using a simple char[] instead of a new-fangled "object".

Without this change, Java scripts longer than 1024 characters will
produce exceptions like:

java.lang.IndexOutOfBoundsException: start 0, end 582, s.length() 442
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:453)
	at java.lang.StringBuilder.append(StringBuilder.java:179)
	at org.scijava.plugins.scripting.java.JavaEngine.getReaderContentsAsString(JavaEngine.java:904)
	at org.scijava.plugins.scripting.java.JavaEngine.eval(JavaEngine.java:169)